todoproject/todoapp/urls.py
from . import views
from django.urls import path
app_name='todoapp'
urlpatterns = [
    path('', views.home,name='home'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('listview/',views.Tasklistview.as_view(),name='listview'),
    path('detail/<int:pk>/',views.Taskdetail.as_view(),name='detail'),
    path('cbvupdate/<int:pk>/',views.updateview.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.deleteview.as_view(),name='cbvdelete')
]

todoproject/todoproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    # urlpatterns += static(settings.MEDIA_URL,
    #                       document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from .models import Task
from django import forms

class Todoforms(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from todoapp.models import Task
from .forms import Todoforms
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import UpdateView,DeleteView
# Create your views here.
class Tasklistview(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task1'

class Taskdetail(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'

class updateview(UpdateView):
    model = Task
    template_name = 'updatenew.html'
    context_object_name = 'task'
    fields = ('name','priority','date')

    def get_success_url(self):
        return reverse_lazy('detail',kwargs={'pk':self.object.id})

class deleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('listview')



def home(request):
    task1 = Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task1':task1})

def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method=='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
    task=Task.objects.get(id=id)
    f=Todoforms(request.POST or None,instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'update.html',{'f':f,'task':task})

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TODO</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
    <form method='POST'>
        {% csrf_token %}
    <p>Are You Sure want to Delete this task</p>
    <button type="submit">Confirm</button>
    </form>
{% endblock %}

todoproject/templates/detail.html
{% extends 'base.html' %}
{% block content %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{task.name}}</h5>
                    <p><b>Priority : {{task.priority}}</b></p>
                    <p><b>{{task.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' task.id %}">Update</a>
                </div>
            </div>
{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <form method="POST" class="p-3 shadow">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control" name="task" placeholder="Enter Task Name">
        </div><br>
        <div class="form-group">
            <input type="text" class="form-control" name="priority" placeholder="Priority">
        </div><br>
        <div class="form-group">
            <input type="date" class="form-control" name="date" placeholder="Enter date">
        </div><br>

            <input type="submit" class="btn btn-success">
        </form>
        </div>
        <div class="col-md-6">
            <h4>Task to be completed</h4>
            {% for i in task1 %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p><b>Priority : {{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">Update</a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>
</div>
<div>

</div>
{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}
    <div style="background-color:aqua;text-align:center">
<form method="POST" >
    {% csrf_token %}
    {{f.as_p}}
    <button class="btn btn-success" type="submit">Confirm</button>
</form>
    </div>
{% endblock %}

todoproject/templates/updatenew.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST" >
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-success" type="submit">Confirm</button>
            </form>
        </div>
    </div>

</div>

{% endblock %}